base-coins:
  - usdt
  - bitcoin
  - ethereum

db-tables:
  public:
    - prices

  prices: DEV_ODS_CG_MARKET.DEV_ALL_TOKEN_METRICS
  btc_summary: DM_EMA_PRICES.EMA200_BTC_SUMMARY
  
  portfolio:
    schema: PORTFOLIO_DYNAMIC_0
  
    input: INPUT
    total: TOTAL
    unrealized: UNREALIZED_HISTORY
    realized_history: REALIZED_HISTORY
    snaphots: SNAPSHOTS
    portfolio_coins: PORTFOLIO_COINS
    metrics-tables:
        beta_bitcoin: METRICS
        corr_bitcoin: METRICS
        beta_ethereum: METRICS
        corr_ethereum: METRICS
    
output:
  first_date: '2023-03-26'
  dict_metric_output:
    roi_usdt: 'roi_usd'
    roi_bitcoin: 'roi_btc'
    roi_ethereum: 'roi_eth'
    beta_bitcoin: beta_btc
    corr_bitcoin: corr_btc
    beta_ethereum: beta_eth
    corr_ethereum: corr_eth
    
google-sheet:
  sheet-id: 1wHCThxTRgdJu2K0TnyFyQs8wUTTQfDumyelyb0QzYCE
  path-to-key-file: '{conf_path}/gs_key.json'

                
 